### ISSUE TITLE
expectFilter without checking filtered value

### ISSUE THREAD

**Issue by leewillis77** [10up/wp_mock#111]
I've just pulled in the dev branch to use the new `expectFilter()` method in some of my tests. (See #110) 

From the documentation, it looks like you *have* to supply the default value to get the expectation to be recognised, e.g. 

```php
// This works
\WP_Mock::expectFilter( 'my_filter', 'default_value' );
// This does not
\WP_Mock::expectFilter( 'my_filter' );
```

Is there any chance of modifying this so that we can assert that the filter was called, without necessarily checking the value passed to that filter. Alternatively, is there a way of type matching the value?

I tried these, but they didn't seem to work:

```php
\WP_Mock::expectFilter( 'my_filter', \WP_Mock\Functions::type( 'string' ) );
\WP_Mock::expectFilter( 'my_filter', \Mockery::any() );
```

**Comment by johnpbloch** [comment]
It's past time to rewrite hooks to use Mockery. They're the oldest part of this library and pre-date the introduction of Mockery. Currently you can't use Mockery type expectations because it basically builds a tree out of the expectations.

My suggestion is that we change this issue to be "Update Hooks to Use Mockery Under the Hood". @ericmann thoughts?

**Comment by johnpbloch** [comment]
(We should keep the same interface that we have, just that this would allow us to also use Mockery type expectations and `\WP_Mock::userFunction()` calls as well.

**Comment by ericmann** [comment]
Closing thus due to age.
