### ISSUE TITLE
PHP dependency on v0.3.0

### ISSUE THREAD

**Issue by bruno-barros** [10up/wp_mock#138]
**Describe the bug**
Trying to install v0.3.0 fails because  doctrine/inflector v1.3.0 requires php ^7.1

**To Reproduce**
1. composer require --dev 10up/wp_mock:0.3.0
2. See error

**Expected behavior**
As I'm on PHP 7.0.32 it should install without problem.

**Screenshots**
https://pasteboard.co/I9g2F0C.png

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by ericmann** [comment]
This is because Composer will automatically default to installing the latest version of PHPUnit when you `composer require` WP_Mock. That version assumes you have a recent version of PHP, and also requires more recent versions of `doctrine/instantiator` (not "inflector" as you mention here).

The `doctrine/inflector` project itself is not a requirement of WP_Mock or any of its dependencies, but there's a chance that _another_ dependency in your project is triggering its inclusion and the inter-relation between `doctrine/instantiator` and your project is forcing an upgrade.

I would suggest hard-coding the versions of PHPUnit, WP_Mock, and even `doctrine/instantiator` that you need for PHP 7.0 compatibility directly in your `composer.json` file:

```{.json}
{
    "require-dev": {
        "doctrine/instantiator": "1.0.5",
        "phpunit/phpunit": "^6",
        "10up/wp_mock": "0.3.0"
    }
}
```

This is the most recent version of Instantiator that works with 7.0 and the explicit version of PHPUnit that WP_Mock 0.3.0 was tested to work with.
