### ISSUE TITLE
Extend TestCase from WP_UnitTestCase instead of \PHPUnit\Framework\TestCase

### ISSUE THREAD

**Issue by iam-mhaseeb** [10up/wp_mock#159]
**Is your feature request related to a problem? Please describe.**
I need factory methods of WordPress in my test but after extending my test from `\WP_Mock\Tools\TestCase` I'm not allowed to use factory methods for the post.

**Describe the solution you'd like**
Extend `\WP_Mock\Tools\TestCase` from `WP_UnitTestCase` instead of `\PHPUnit\Framework\TestCase` because under the hood it also extends from ``\PHPUnit\Framework\TestCase`.

**Comment by unfulvio-godaddy** [comment]
@iam-mhaseeb which features of the WP_Mock TestCase do your tests requires?

Perhaps we could split some methods from that TestCase into traits.

I believe WP_Mock should not extend `WP_UnitTestCase` because the `WP_UnitTestCase_Base` abstract it extends contains a lot of WordPress-specific  functions and we'd introduce a problematic dependency in WP_Mock.

If however you are designing your own TestCase object extending `WP_UnitTestCase`, if WP_Mock can provide some traits for the functions you'd like to use, we can still have WP_Mock TestCase use those traits which could be implemented by third parties as well.

**Comment by unfulvio-godaddy** [comment]
After looking again into this issue, I'm not sure if the idea of splitting some methods into traits could work or be of any help at all to your original question. WP_Mock is tightly coupled with Mockery, and to specific versions of PhpUnit, while WP test cases seem not to account for it being more close to integration tests than pure unit tests as per https://core.trac.wordpress.org/browser/trunk/tests/phpunit/README.txt

> phpunit will initialize and install a (more or less) complete running copy of WordPress each time it is run. This makes it possible to run functional interface and module tests against a fully working database and codebase, as opposed to pure unit tests with mock objects and stubs.

Also check out this other thread: https://github.com/10up/wp_mock/issues/49

Having WP_Mock own `TestCase` extend `WP_UnitTestCase` will introduce a dependency on the WordPress test suite which would break existing use cases where WP_Mock `TestCase`. 

Perhaps another way of looking at your original question could be to build missing features you're looking for into WP_Mock. You could also integrate WP_Mock in your own test case that extends `WP_UnitTestCase` by overriding setUp/tearDown methods and using the `WP_Mock` main class static methods as appropriate. 

I'm closing this for now, but please feel free to re-open this issue or open another issue if there's something else we could explore. Thank you!
