### ISSUE TITLE
Latest release has not been published to packagist.

### ISSUE THREAD

**Issue by earthlingdavey** [10up/wp_mock#243]
## Bug report 

Latest release has not been published to packagist.

### Replication steps 

On https://packagist.org/packages/10up/wp_mock 1.0.0 is the newest available version

### Expected behavior 

1.0.1 is the newest available version

**Comment by unfulvio-godaddy** [comment]
hey @EarthlingDavey thanks for reporting this! we thought we had this fixed in #242 but evidently the packagist configuration didn't auto update based on the git tag; I have opened a new PR to set the version in composer instead: #244 

in the meantime you could tweak your own composer config to force using the git tag instead - sorry for the inconvenience

**Comment by unfulvio-godaddy** [comment]
seems like we had to retag release on github to have changes picked up on packagist as well! all good! I am going to close this now but feel free to reopen if you still having issues with WP_Mock or have feedback, thank you

**Comment by earthlingdavey** [comment]
Hey, no problem. Thanks a lot for the package, I really appreciate it!

Thanks for being so quick to respond, there's really no need to apologise for any inconvenience!

I'll keep in touch with any further feedback. 

Have a good evening in Taiwan! Cheers from Wales! ✌️
