### ISSUE TITLE
Throw Exception when handle_function fails

### ISSUE THREAD

**Issue by sirbrillig** [10up/wp_mock#52]
When a function is mocked using `Functions::create_function()`, two things are created:

1. The actual function is defined using `eval()`
2. The function handler is bound using `Handler:register_handler()`

When the test is complete and `Functions::flush()` is called, it removes the
handler, but nothing removes the function itself, which will continue to call
`Handler::handle_function()` in later tests, except that this will now be a
noop.

This can create problems when, for example, one test mocks a function to allow a
certain series of function calls, and then a later test also uses that series of
function calls, but does not mock the function. In this case, if the first test
is run before the second test, they will both pass, but if the second test is
run first (or in isolation), it will fail because it calls an undefined
function. Test Mocks should not cause tests to fail if run in different order.

While it may be impossible to replicate a call to an undefined function, we can
simulate it by throwing an Exception. I'd suggest a change that causes
`Handler::handle_function()` to throw an Exception if it doesn't find a matching
handler.

Example:

```php
<?php

class SomeClass {
  public function do_something( $times ) {
    $user = wp_get_current_user();
    //...
    return true;
  }
}

class MyTestClass extends PHPUnit_Framework_TestCase {
  public function setUp() {
    \WP_Mock::setUp();
    $this->something = new SomeClass();
  }

  public function tearDown() {
    \WP_Mock::tearDown();
  }

  public function test_do_something() {
    \WP_Mock::wpFunction( 'wp_get_current_user' );
    $this->assertTrue( $this->something->do_something( 1 ) );
  }

  public function test_do_something_again() {
    $this->assertTrue( $this->something->do_something( 2 ) ); // This should cause a fatal error, but it does not if run after the previous test
  }
}
```

**Comment by johnpbloch** [comment]
Hi @sirbrillig,

Thanks for your enhancement suggestion! As you correctly surmised, it's not possible to undefine a function in PHP (at least without the runkit extension, and that's just not something we want to deal with in WP Mock). For functions defined by WP Mock using `eval()`, you can test for conditions where the function is undefined using PHPUnit's process isolation feature. Add `@runInSeparateProcess` to the docblock of a single test to run it in a unique process, or add `@runTestsInSeparteProcesses` the the docblock of the class to run all of that class' tests in isolation.

Regarding the addition of an exception being thrown when the function is called without an expectation attached, this is absolutely something we are going to add in a limited capacity. This is half of the functionality we want to add as part of #11 (Add a strict mode). This will let developers turn strict mode on, which will throw exceptions for unexpected uses of functions defined through WP Mock, as well as things like using common WP variables (e.g. `$wpdb` from the global scope without first setting their state up in the test.

I'm going to go ahead and close this as a duplicate, since it's pretty much covered by #11.

**Comment by sirbrillig** [comment]
Thanks! I didn't notice the overlap with that issue, and adding a strict mode sounds like a good solution.
