### ISSUE TITLE
Should lack of wpPassthruFunction generate fatal errors during testing?

### ISSUE THREAD

**Issue by sc0ttkclark** [10up/wp_mock#63]
It seems to me that at most, there could be warnings or notices generated for things not properly mocked up for passing thru or mocking things like esc_attr / esc_html / etc.

It also seems pretty difficult to rectify these when running tests results in fatals where a function doesn't exist in the namespace, but it's a global WP function.

Should there be a way to enable tests to run as expected, with notices thrown out for things that are not _covered_?

**Comment by ericmann** [comment]
Even though things like `esc_attr`, `esc_html`, `__`, etc are global functions, they're still global functions - they are effectively the same as any other function that would be defined in a plugin/theme, they just happen to be defined by Core.

On the one hand, I want to say that no, there should always be an error. The purist in me feels that any use of any global function should be declared with a `@uses` block in documentation and then properly mocked in testing.

On the other hand, I've been bit by this same issue enough in the past that the pragmatist in me thinks we could define a default handler to catch any WP Core passthru functions and handle them appropriately. Perhaps this could be built into the base test case. I'm thinking, though that any use of such a default should automatically mark the test that uses it as risky, but off the top of my head I'm not sure.

Thoughts?

**Comment by johnpbloch** [comment]
I'm generally in agreement with Eric on this point. I think any functions that we can reasonably expect someone might use in the global scope (instead of inside a function) can be added by WP Mock by default. I don't think escaping and i18n functions really fall into that category.

That being said, once we have #11 completed, I think that will greatly lower the bar as to which WP functions we'll include by default. So, I think this proposal is a "maybe" right now, and a "pretty much yes" after #11 gets finished.

**Comment by johnpbloch** [comment]
Ok, some preliminary work has gone into this feature. At least enough that I think we're probably at the point where we can move forward with merging and add more default functions as necessary. Check out #76 for the code.
