### ISSUE TITLE
WPMock::wpFunction appears incompatible with allowMockingNonExistentMethods

### ISSUE THREAD

**Issue by dgmstuart** [10up/wp_mock#77]
I'm having difficulty with WP_Mock when I'm disabling mocking nonexistent methods:

Mockery has a setting that prevents you creating imaginary tests which mock methods which don't exist:

```php
\Mockery::getConfiguration()->allowMockingNonExistentMethods(false);
```
When I enable this and use e.g.
```php
\WP_Mock::wpFunction('get_posts', ...
```
Mockery complains because the WP methods I'm mocking don't exist on the objects in question (presumably because they're global functions). Here's the error:

    Mockery's configuration currently forbids mocking the method get_posts as it does not exist on the class or object being mocked

I'm working around this by selectively disabling this setting in tests which use WP_Mock (I'm using peridot for tests):

```php
beforeEach(function() {
    \WP_Mock::setUp();
    \Mockery::getConfiguration()->allowMockingNonExistentMethods(true);
});

afterEach(function() {
    \WP_Mock::tearDown();
    \Mockery::getConfiguration()->allowMockingNonExistentMethods(false);
});
```

Does anyone know of a better approach? Or is the solution to patch WP_Mock such that mockery ignores these methods when checking for mocking nonexistent methods?

**Comment by johnpbloch** [comment]
If this is something that can be overridden on a per-mock object level, then yes, I think it's reasonable to patch WP_Mock so that the internal mock objects it uses all explicitly state that they support mocking non-existent methods.

On an unrelated note, this is the first I've seen of somebody using WP_Mock with a testing framework other than PHPUnit. Since WP_Mock is meant to be used specifically with PHPUnit, there's no guarantee that it will work in other contexts, especially as we continue to tighten that integration.

**Comment by dgmstuart** [comment]
@johnpbloch Thanks for the response. 

That's interesting to know - about it being intended for use in PHPUnit: maybe worth a mention in the readme? Out of interest, what is it that makes this library specific to PHPUnit?

**Comment by johnpbloch** [comment]
> maybe worth a mention in the readme?

Probably :)

> Out of interest, what is it that makes this library specific to PHPUnit?

It comes with several extensions to PHPUnit already. These don't necessarily make it specifically for use only with PHPUnit, but as more of these integrations are built it'll touch more and more of the API. For example, there's a `TestCase` class that extends `PHPUnit_Framework_TestCase` which is where most of the test-level development is going these days, rather than the `WP_Mock` class. It's also likely that we'll start requiring that `WP_Mock::setUp()` also injects a testcase object to better give the library the ability to integrate with the test itself.

**Comment by dgmstuart** [comment]
Interesting. I guess perhaps ideally we'd have two libraries: `WP_Mock\Core`, and `WP_Mock\PHPUnit`, which would add the deeper integrations, but I can appreciate that running one open-source project is enough work on its own.

**Comment by johnpbloch** [comment]
Yeah, for a while we were looking into ripping out the guts of WP Mock and replacing it with [Brain Monkey](http://brain-wp.github.io/BrainMonkey/). At the time the lack of PHP 5.3 support was a blocker, but I'm not so sure any more.
