### ISSUE TITLE
Which branch should be used?

### ISSUE THREAD

**Issue by jpresley23** [10up/wp_mock#82]
The repository defaults to showing `dev` branch and it looks like that is the branch with active development. `master` hasn't been updated in a few years. Which branch do you recommend we install?

**Comment by johnpbloch** [comment]
`dev` is the recommended branch.

**Comment by jpresley23** [comment]
Thanks for the clarification. Should the installation instructions be updated?

**Comment by XedinUnknown** [comment]
Same question.

When accessing the repo via web interface, `dev` appears to be the default branch. On that branch, it says to depend on `dev-master`. But the usage instructions below are wrong for `dev-master`. As an example, `WP_Mock::activateStrictMode()` does not exist, and `WP_Mock::userFunction()` cannot be used for WP functions.
Also, unless feeling adventurous, developers should not depend on a branch, the head of which can change, and should depend on a version constraint, e.g. `^0.1.1`. Otherwise, they risk suddenly one day not being able to run tests, because WP Mock can break BC unexpectedly. However, the instructions say to depend on `dev-master`...

**Comment by csrui** [comment]
If dev is the recommended branch shouldn't the readme reflect that?
```
composer require --dev 10up/wp_mock:dev-master
```

**Comment by lloc** [comment]
`composer require --dev 10up/wp_mock:dev-master`

seems not to install the expected branch. I had to use 

`composer require --dev 10up/wp_mock:dev-dev`

instead.

**Comment by ericmann** [comment]
Readme has been updated. We'll be eventually (I hope) moving to tagged releases in the near future to help further clarify things.
